// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJBxGSlJDTufhZVZy7ozPEe-D0nVYBhUg',
    appId: '1:274518596440:web:56dde39d48e2c71e1a632d',
    messagingSenderId: '274518596440',
    projectId: 'part-107-82ca6',
    authDomain: 'part-107-82ca6.firebaseapp.com',
    storageBucket: 'part-107-82ca6.appspot.com',
    measurementId: 'G-Q3QYFD3Y6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6m7uN8Iq3qsV5vAkYbbWFXSXN29fK8jQ',
    appId: '1:274518596440:android:33a467d5b89b87a71a632d',
    messagingSenderId: '274518596440',
    projectId: 'part-107-82ca6',
    storageBucket: 'part-107-82ca6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwwOzA76Ng5C_mgxloc_EWZrI5JhC0r9c',
    appId: '1:274518596440:ios:53d2eb49bcdc945e1a632d',
    messagingSenderId: '274518596440',
    projectId: 'part-107-82ca6',
    storageBucket: 'part-107-82ca6.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );
}
